apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30090
    protocol: TCP
    name: console
  - port: 9000
    targetPort: 9000
    nodePort: 30091
    protocol: TCP
    name: api
  selector:
    app: minio
